Use boe es, redis, mysql, tos, tcc

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -10,7 +10,7 @@ services:
       MYSQL_DATABASE: ${MYSQL_DATABASE:-opencoze}
       MYSQL_USER: ${MYSQL_USER:-coze}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD:-coze123}
-    profiles: [ 'middleware', 'mysql-setup', 'mysql' ]
+    profiles: ['middleware', 'mysql-setup', 'mysql']
     env_file: *env_file
     ports:
       - '3306:3306'
@@ -42,7 +42,7 @@ services:
     container_name: coze-redis
     user: root
     privileged: true
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     environment:
       - REDIS_AOF_ENABLED=${REDIS_AOF_ENABLED:-no}
@@ -72,7 +72,7 @@ services:
       mysql-setup-init-sql:
         condition: service_completed_successfully
     healthcheck:
-      test: [ 'CMD', 'redis-cli', 'ping' ]
+      test: ['CMD', 'redis-cli', 'ping']
       interval: 5s
       timeout: 10s
       retries: 10
@@ -80,119 +80,120 @@ services:
     networks:
       - coze-network
 
-  rocketmq-namesrv:
-    image: apache/rocketmq:5.3.2
-    container_name: coze-rocketmq-namesrv
-    privileged: true
-    user: root
-    profiles: [ 'middleware' ]
-    env_file: *env_file
-    ports:
-      - '9876:9876'
-    volumes:
-      - ./data/rocketmq/namesrv/logs:/home/rocketmq/logs:rw,Z
-      - ./data/rocketmq/namesrv/store:/home/rocketmq/store:rw,Z
-    environment:
-      - ALLOW_ANONYMOUS_LOGIN=yes
-    command: >
-      bash -c "
-        # Set proper permissions for data directories
-        mkdir -p /home/rocketmq/logs /home/rocketmq/store
-        mkdir -p /home/rocketmq/logs/rocketmqlogs
-        touch /home/rocketmq/logs/rocketmqlogs/tools.log
-        touch /home/rocketmq/logs/rocketmqlogs/tools_default.log
+  # rocketmq-namesrv:
+  #   image: apache/rocketmq:5.3.2
+  #   container_name: coze-rocketmq-namesrv
+  #   privileged: true
+  #   user: root
+  #   profiles: ['middleware']
+  #   env_file: *env_file
+  #   ports:
+  #     - '9876:9876'
+  #   volumes:
+  #     - ./data/rocketmq/namesrv/logs:/home/rocketmq/logs:rw,Z
+  #     - ./data/rocketmq/namesrv/store:/home/rocketmq/store:rw,Z
+  #   environment:
+  #     - ALLOW_ANONYMOUS_LOGIN=yes
+  #   command: >
+  #     bash -c "
+  #       # Set proper permissions for data directories
+  #       mkdir -p /home/rocketmq/logs /home/rocketmq/store
+  #       mkdir -p /home/rocketmq/logs/rocketmqlogs
+  #       touch /home/rocketmq/logs/rocketmqlogs/tools.log
+  #       touch /home/rocketmq/logs/rocketmqlogs/tools_default.log
 
-        chown -R rocketmq:rocketmq /home/rocketmq/logs /home/rocketmq/store
-        chmod g+s /home/rocketmq/logs /home/rocketmq/store
+  #       chown -R rocketmq:rocketmq /home/rocketmq/logs /home/rocketmq/store
+  #       chmod g+s /home/rocketmq/logs /home/rocketmq/store
 
-        echo 'Starting RocketMQ NameServer...'
-        sh mqnamesrv
-      "
-    healthcheck:
-      test: [ 'CMD', 'sh', 'mqadmin', 'clusterList', '-n', 'localhost:9876' ]
-      interval: 5s
-      timeout: 10s
-      retries: 10
-      start_period: 10s
-    networks:
-      - coze-network
-  rocketmq-broker:
-    image: apache/rocketmq:5.3.2
-    container_name: coze-rocketmq-broker
-    privileged: true
-    user: root
-    profiles: [ 'middleware' ]
-    env_file: *env_file
-    ports:
-      - '10909:10909'
-      - '10911:10911'
-      - '10912:10912'
-    volumes:
-      - ./data/rocketmq/broker/logs:/home/rocketmq/logs:rw,Z
-      - ./data/rocketmq/broker/store:/home/rocketmq/store:rw,Z
-      - ./volumes/rocketmq/broker.conf:/home/rocketmq/conf/broker.conf:rw,Z
-    networks:
-      - coze-network
-    command: >
-      bash -c '
-        # Set proper permissions
-        mkdir -p /home/rocketmq/logs/rocketmqlogs /home/rocketmq/store
-        touch /home/rocketmq/logs/rocketmqlogs/tools.log \
-              /home/rocketmq/logs/rocketmqlogs/tools_default.log
-        chown -R rocketmq:rocketmq /home/rocketmq/logs /home/rocketmq/store
-        chmod g+s /home/rocketmq/logs /home/rocketmq/store
+  #       echo 'Starting RocketMQ NameServer...'
+  #       sh mqnamesrv
+  #     "
+  #   healthcheck:
+  #     test: ['CMD', 'sh', 'mqadmin', 'clusterList', '-n', 'localhost:9876']
+  #     interval: 5s
+  #     timeout: 10s
+  #     retries: 10
+  #     start_period: 10s
+  #   networks:
+  #     - coze-network
+  # rocketmq-broker:
+  #   image: apache/rocketmq:5.3.2
+  #   container_name: coze-rocketmq-broker
+  #   privileged: true
+  #   user: root
+  #   profiles: ['middleware']
+  #   env_file: *env_file
+  #   ports:
+  #     - '10909:10909'
+  #     - '10911:10911'
+  #     - '10912:10912'
+  #   volumes:
+  #     - ./data/rocketmq/broker/logs:/home/rocketmq/logs:rw,Z
+  #     - ./data/rocketmq/broker/store:/home/rocketmq/store:rw,Z
+  #     - ./volumes/rocketmq/broker.conf:/home/rocketmq/conf/broker.conf:rw,Z
+  #   networks:
+  #     - coze-network
+  #   command: >
+  #     bash -c '
+  #       # Set proper permissions
+  #       mkdir -p /home/rocketmq/logs/rocketmqlogs /home/rocketmq/store
+  #       touch /home/rocketmq/logs/rocketmqlogs/tools.log \
+  #             /home/rocketmq/logs/rocketmqlogs/tools_default.log
+  #       chown -R rocketmq:rocketmq /home/rocketmq/logs /home/rocketmq/store
+  #       chmod g+s /home/rocketmq/logs /home/rocketmq/store
 
-        echo "Starting RocketMQ Broker..."
-        sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/conf/broker.conf &
+  #       echo "Starting RocketMQ Broker..."
+  #       sh mqbroker -n rocketmq-namesrv:9876 -c /home/rocketmq/conf/broker.conf &
 
-        echo "Waiting for Broker registration..."
-        broker_ready=false
-        for i in {1..60}; do
-          if sh mqadmin clusterList -n rocketmq-namesrv:9876 \
-             | grep -q "DefaultCluster.*broker-a"; then
-            echo "Registered."
-            broker_ready=true
-            break
-          fi
-          echo "Not ready, retry $$i/60..."
-          sleep 1
-        done
+  #       echo "Waiting for Broker registration..."
+  #       broker_ready=false
+  #       for i in {1..60}; do
+  #         if sh mqadmin clusterList -n rocketmq-namesrv:9876 \
+  #            | grep -q "DefaultCluster.*broker-a"; then
+  #           echo "Registered."
+  #           broker_ready=true
+  #           break
+  #         fi
+  #         echo "Not ready, retry $$i/60..."
+  #         sleep 1
+  #       done
 
-        if [ "$$broker_ready" = false ]; then
-          echo "ERROR: registration timed out."
-          exit 1
-        fi
+  #       if [ "$$broker_ready" = false ]; then
+  #         echo "ERROR: registration timed out."
+  #         exit 1
+  #       fi
 
-        echo "Creating topics..."
-        for t in opencoze_knowledge opencoze_search_app opencoze_search_resource \
-                  %RETRY%cg_knowledge %RETRY%cg_search_app %RETRY%cg_search_resource; do
-          sh mqadmin updateTopic -n rocketmq-namesrv:9876 \
-            -c DefaultCluster -t "$$t"
-        done
+  #       echo "Creating topics..."
+  #       for t in opencoze_knowledge opencoze_search_app opencoze_search_resource \
+  #                 %RETRY%cg_knowledge %RETRY%cg_search_app %RETRY%cg_search_resource; do
+  #         sh mqadmin updateTopic -n rocketmq-namesrv:9876 \
+  #           -c DefaultCluster -t "$$t"
+  #       done
 
-        touch /tmp/rocketmq_ready
-        echo "Broker started successfully."
-        wait
-      '
-    depends_on:
-      - rocketmq-namesrv
-    healthcheck:
-      test: [ 'CMD-SHELL', '[ -f /tmp/rocketmq_ready ]' ]
-      interval: 10s
-      timeout: 10s
-      retries: 10
-      start_period: 10s
+  #       touch /tmp/rocketmq_ready
+  #       echo "Broker started successfully."
+  #       wait
+  #     '
+  #   depends_on:
+  #     - rocketmq-namesrv
+  #   healthcheck:
+  #     test: ['CMD-SHELL', '[ -f /tmp/rocketmq_ready ]']
+  #     interval: 10s
+  #     timeout: 10s
+  #     retries: 10
+  #     start_period: 10s
 
   elasticsearch:
     image: bitnami/elasticsearch:8.18.0
     container_name: coze-elasticsearch
     user: root
     privileged: true
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     environment:
+      - TEST=1
       # Add Java certificate trust configuration
-      - ES_JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Djavax.net.ssl.trustAll=true -Xms4096m -Xmx4096m
+      # - ES_JAVA_OPTS=-Djdk.tls.client.protocols=TLSv1.2 -Dhttps.protocols=TLSv1.2 -Djavax.net.ssl.trustAll=true -Xms4096m -Xmx4096m
     ports:
       - '9200:9200'
     volumes:
@@ -249,47 +250,12 @@ services:
         echo -e "⏳ Adjusting Elasticsearch disk watermark settings..."
       "
 
-  kibana:
-    image: bitnami/kibana:8.18.0
-    container_name: coze-kibana
-    user: root
-    privileged: true
-    profiles: [ 'middleware' ]
-    env_file: *env_file
-    ports:
-      - '5601:5601'
-    environment:
-      # - ELASTICSEARCH_HOSTS=http://coze-elasticsearch:9200
-      - KIBANA_ELASTICSEARCH_URL=coze-elasticsearch
-    volumes:
-      - ./data/bitnami/kibana:/bitnami/kibana:rw,Z
-    command: >
-      bash -c "
-        /opt/bitnami/scripts/kibana/setup.sh
-        # Set proper permissions for data directories
-        chown -R kibana:kibana /bitnami/kibana
-        chmod g+s /bitnami/kibana
-
-        exec /opt/bitnami/scripts/kibana/entrypoint.sh /opt/bitnami/scripts/kibana/run.sh
-      "
-    depends_on:
-      elasticsearch:
-        condition: service_healthy
-    healthcheck:
-      test: [ 'CMD', 'curl', '-f', 'http://localhost:5601/api/status' ]
-      interval: 5s
-      timeout: 10s
-      retries: 10
-      start_period: 10s
-    networks:
-      - coze-network
-
   minio:
-    image: minio/minio:latest
+    image: minio/minio:RELEASE.2025-06-13T11-33-47Z-cpuv1
     container_name: coze-minio
     user: root
     privileged: true
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     ports:
       - '9000:9000'
@@ -302,7 +268,11 @@ services:
       MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET:-opencoze},${MINIO_DEFAULT_BUCKETS:-milvus}
     command: server /data --console-address ":9001"
     healthcheck:
-      test: [ 'CMD-SHELL', 'curl -f http://localhost:9000/minio/health/live' ]
+      test:
+        [
+          'CMD-SHELL',
+          '/usr/bin/mc alias set health_check http://localhost:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} && /usr/bin/mc ready health_check',
+        ]
       interval: 30s
       timeout: 10s
       retries: 3
@@ -315,7 +285,7 @@ services:
     container_name: coze-etcd
     user: root
     privileged: true
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     environment:
       - ETCD_AUTO_COMPACTION_MODE=revision
@@ -338,7 +308,7 @@ services:
         exec /opt/bitnami/scripts/etcd/entrypoint.sh /opt/bitnami/scripts/etcd/run.sh
       "
     healthcheck:
-      test: [ 'CMD', 'etcdctl', 'endpoint', 'health' ]
+      test: ['CMD', 'etcdctl', 'endpoint', 'health']
       interval: 5s
       timeout: 10s
       retries: 10
@@ -351,7 +321,7 @@ services:
     image: milvusdb/milvus:v2.5.10
     user: root
     privileged: true
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     command: >
       bash -c "
@@ -373,9 +343,8 @@ services:
       LOG_LEVEL: debug
     volumes:
       - ./data/milvus:/var/lib/milvus:rw,Z
-      - ./volumes/milvus/milvus.yml:/milvus/configs/milvus.yml:ro,Z
     healthcheck:
-      test: [ 'CMD', 'curl', '-f', 'http://localhost:9091/healthz' ]
+      test: ['CMD', 'curl', '-f', 'http://localhost:9091/healthz']
       interval: 5s
       timeout: 10s
       retries: 10
@@ -390,10 +359,60 @@ services:
         condition: service_healthy
     networks:
       - coze-network
+  nsqlookupd:
+    image: nsqio/nsq:v1.2.1
+    container_name: coze-nsqlookupd
+    command: /nsqlookupd
+    profiles: ['middleware']
+    ports:
+      - '4160:4160'
+      - '4161:4161'
+    networks:
+      - coze-network
+    healthcheck:
+      test: ['CMD-SHELL', 'nsqlookupd --version']
+      interval: 5s
+      timeout: 10s
+      retries: 10
+      start_period: 10s
+
+  nsqd:
+    image: nsqio/nsq:v1.2.1
+    container_name: coze-nsqd
+    command: /nsqd --lookupd-tcp-address=coze-nsqlookupd:4160 --broadcast-address=coze-nsqd
+    profiles: ['middleware']
+    ports:
+      - '4150:4150'
+      - '4151:4151'
+    depends_on:
+      nsqlookupd:
+        condition: service_healthy
+    networks:
+      - coze-network
+    healthcheck:
+      test: ['CMD-SHELL', '/nsqd --version']
+      interval: 5s
+      timeout: 10s
+      retries: 10
+      start_period: 10s
+
+  nsqadmin:
+    image: nsqio/nsq:v1.2.1
+    container_name: coze-nsqadmin
+    command: /nsqadmin --lookupd-http-address=coze-nsqlookupd:4161
+    profiles: ['middleware']
+    ports:
+      - '4171:4171'
+    depends_on:
+      nsqlookupd:
+        condition: service_healthy
+    networks:
+      - coze-network
+
   elasticsearch-setup:
     image: alpine/curl:8.12.1
     container_name: coze-elasticsearch-setup
-    profiles: [ 'middleware', 'volcano-setup' ]
+    profiles: ['middleware', 'volcano-setup']
     env_file: *env_file
     volumes:
       - ./volumes/elasticsearch/setup_es.sh:/setup_es.sh
@@ -409,9 +428,9 @@ services:
       - coze-network
     restart: 'no'
   minio-setup:
-    image: minio/mc
+    image: minio/mc:RELEASE.2025-05-21T01-59-54Z-cpuv1
     container_name: coze-minio-setup
-    profiles: [ 'middleware' ]
+    profiles: ['middleware']
     env_file: *env_file
     depends_on:
       minio:
@@ -434,7 +453,7 @@ services:
   mysql-setup-schema:
     image: arigaio/atlas:0.35.0-community-alpine
     container_name: coze-mysql-setup-schema
-    profiles: [ 'middleware', 'mysql-setup', 'run-server' ]
+    profiles: ['middleware', 'mysql-setup', 'run-server']
     env_file: *env_file
     volumes:
       - ./atlas/opencoze_latest_schema.hcl:/opencoze_latest_schema.hcl
@@ -469,7 +488,7 @@ services:
   mysql-setup-init-sql:
     image: mysql:8.4.5
     container_name: coze-mysql-setup-init-sql
-    profiles: [ 'middleware', 'mysql-setup', 'run-server', 'volcano-setup' ]
+    profiles: ['middleware', 'mysql-setup', 'run-server', 'volcano-setup']
     env_file: *env_file
     command:
       - /bin/sh
@@ -497,34 +516,14 @@ services:
     networks:
       - coze-network
     restart: 'no'
-  tos-setup:
-    image: alpine/curl:8.12.1
-    container_name: coze-tos-setup
-    profiles: [ 'volcano-setup' ]
-    env_file: *env_file
-    volumes:
-      - ./volumes/minio/default_icon/:/default_icon
-      - ./volumes/minio/official_plugin_icon/:/official_plugin_icon
-      - ./volumes/minio/tosutil:/tosutil
-    entrypoint: >
-      /bin/sh -c  "
-        (/tosutil version && \
-        /tosutil config -i ${TOS_ACCESS_KEY} -k ${TOS_SECRET_KEY} -e ${TOS_ENDPOINT} -re ${TOS_REGION} && \
-        /tosutil cp /default_icon tos://${STORAGE_BUCKET} -r && \
-        /tosutil cp /official_plugin_icon tos://${STORAGE_BUCKET} -r && \
-        echo 'upload files to tos complete: Files uploaded to ${STORAGE_BUCKET} bucket.') || exit 1; \
-      "
-    networks:
-      - coze-network
-    restart: 'no'
 
   coze-server:
     # build:
-    #   c6ntext: ../
+    #   context: ../
     #   dockerfile: backend/Dockerfile
-    image: fanlv/opencoze:0.1.1
+    image: opencoze/opencoze:latest
     container_name: coze-server
-    profiles: [ 'run-server' ]
+    profiles: ['run-server']
     env_file: *env_file
     environment:
       LISTEN_ADDR: 0.0.0.0:8888
@@ -532,9 +531,10 @@ services:
       - coze-network
     ports:
       - '8888:8888'
+      - '8889:8889'
     volumes:
-      - ../docker/.env:/app/.env
-      - ../backend/conf:/app/resources/conf
+      - .env:/app/.env
+      # - ../backend/conf:/app/resources/conf
       # - ../backend/static:/app/resources/static
     depends_on:
       mysql:
@@ -557,37 +557,7 @@ services:
         condition: service_completed_successfully
       mysql-setup-init-sql:
         condition: service_completed_successfully
-    command: [ '/app/bootstrap.sh' ]
-    deploy:
-      resources:
-        limits:
-          cpus: '8'
-          memory: 16G
-        reservations:
-          cpus: '2'
-          memory: 4G
-  coze-server-on-volcano:
-    image: fanlv/opencoze:0.1.1
-    container_name: coze-server-on-volcano
-    profiles: [ 'volcano-server' ]
-    env_file: *env_file
-    environment:
-      LISTEN_ADDR: 0.0.0.0:80
-    networks:
-      - coze-network
-    ports:
-      - '80:80'
-    volumes:
-      - ../docker/.env:/app/.env
-      - ../backend/conf:/app/resources/conf
-    depends_on:
-      tos-setup:
-        condition: service_completed_successfully
-      elasticsearch-setup:
-        condition: service_completed_successfully
-      mysql-setup-init-sql:
-        condition: service_completed_successfully
-    command: [ '/app/bootstrap.sh' ]
+    command: ['/app/bootstrap.sh']
     deploy:
       resources:
         limits:
