feat: impl GetModelList api
* feat: regen api code


* feat: impl GetModelList api


See merge request: !347

diff --git a/docker/docker-compose.yml b/docker/docker-compose.yml
--- a/docker/docker-compose.yml
+++ b/docker/docker-compose.yml
@@ -164,20 +164,22 @@ services:
         # Create plugin directory
         mkdir -p /bitnami/elasticsearch/plugins;
       
-        # Download plugin package locally
-        echo 'Downloading smartcn plugin...';
-        curl -k -L -o /tmp/analysis-smartcn.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-smartcn/analysis-smartcn-8.18.0.zip
-        if [[ "$?" != "0" ]]; then
-          echo 'Plugin download failed, exiting installation';
-          exit 1;
-        fi;
-      
         # Unzip plugin to plugin directory and set correct permissions
         echo 'Installing smartcn plugin...';
         if [ ! -d /opt/bitnami/elasticsearch/plugins/analysis-smartcn ]; then
+
+          # Download plugin package locally
+          echo 'Downloading smartcn plugin...';
+          curl -k -L -o /tmp/analysis-smartcn.zip https://artifacts.elastic.co/downloads/elasticsearch-plugins/analysis-smartcn/analysis-smartcn-8.18.0.zip
+          if [[ "$?" != "0" ]]; then
+            echo 'Plugin download failed, exiting installation';
+            exit 1;
+          fi;
+
           elasticsearch-plugin install file:///tmp/analysis-smartcn.zip
           if [[ "$?" != "0" ]]; then
             echo 'Plugin installation failed, exiting operation';
+            rm -rf /opt/bitnami/elasticsearch/plugins/analysis-smartcn
             exit 1;
           fi;
           rm -f /tmp/analysis-smartcn.zip;
